services:
  db:
    image: postgres:16-alpine3.22
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

  nest-backend:
    image: commonex-nest-backend
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER_NAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: postgres
    depends_on:
      - db

  next-web:
    image: commonex-next-web
    restart: always

  nginx:
    image: nginx:1.29.1-alpine3.22
    restart: always
    ports:
      - "8080:80"
    volumes:
      - ./nginx-prod.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - nest-backend
      - next-web

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
